### ISSUE TITLE
Prevent same address from getting multiple drips

### ISSUE THREAD

**Issue by schmidsi** [melonproject/faucet#5]
Maybe give only twice a day
Limit ethereum addresss
Limit IP address
Maybe even try to fingerprint the browser: https://github.com/Valve/fingerprintjs2

I think it's ok to give to the same address twice a day. Maybe they screw up at the first try. But we really need to limit it.

**Comment by GauthamN** [comment]
I think a combination of limiting addresses and ip would partly stop spam attacks. Exponential backoff is also a good idea instead of just limiting address. If there's really a need for addresses already having considerable k-eth and mln needing more, then we should go with the exponential backoff method.
